name: Update Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game Image
        uses: platane/plt/github-action@v2
        with:
          github_user: 'kanishka-trivedi'  # Replace with your username
          github_repo: 'kanishka-trivedi'  # Replace with your repo name
          file_name: 'github-snake.svg'
          html: false  # We don't need an HTML page
