name: Generate Snake Game Image

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game Image
        uses: platane/plt/github-action@v2
        with:
          github_user: 'Kanishka'  # Replace with your username
          github_repo: 'Kanishka-Trivedi'  # Replace with your repo name
          file_name: 'github-snake.svg'  # This will be the file created
          html: false  # We don't need an HTML page, just the SVG image
